set_property PACKAGE_PIN W5 [get_ports clk_in]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
	
	
set_property PACKAGE_PIN V17 [get_ports {switch[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]
set_property PACKAGE_PIN V16 [get_ports {switch[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property PACKAGE_PIN W16 [get_ports {switch[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property PACKAGE_PIN W17 [get_ports {switch[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property PACKAGE_PIN W15 [get_ports {switch[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
	
	set_property PACKAGE_PIN V15 [get_ports rst]					
	set_property IOSTANDARD LVCMOS33 [get_ports rst]
#set_property PACKAGE_PIN W14 [get_ports {instAddr[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {instAddr[0]}]
#set_property PACKAGE_PIN W13 [get_ports {instAddr[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {instAddr[1]}]
#set_property PACKAGE_PIN V2 [get_ports {instAddr[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {instAddr[2]}]
#set_property PACKAGE_PIN T3 [get_ports {instAddr[3]}]	
#	set_property IOSTANDARD LVCMOS33 [get_ports {instAddr[3]}]
#	set_property PACKAGE_PIN T2 [get_ports {instAddr[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {instAddr[4]}]
	
set_property PACKAGE_PIN U16 [get_ports {reg_value[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[0]}]
set_property PACKAGE_PIN E19 [get_ports {reg_value[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[1]}]
set_property PACKAGE_PIN U19 [get_ports {reg_value[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[2]}]
set_property PACKAGE_PIN V19 [get_ports {reg_value[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[3]}]
set_property PACKAGE_PIN W18 [get_ports {reg_value[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[4]}]
set_property PACKAGE_PIN U15 [get_ports {reg_value[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[5]}]
set_property PACKAGE_PIN U14 [get_ports {reg_value[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[6]}]
set_property PACKAGE_PIN V14 [get_ports {reg_value[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[7]}]
set_property PACKAGE_PIN V13 [get_ports {reg_value[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[8]}]
set_property PACKAGE_PIN V3 [get_ports {reg_value[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[9]}]
set_property PACKAGE_PIN W3 [get_ports {reg_value[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[10]}]
set_property PACKAGE_PIN U3 [get_ports {reg_value[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[11]}]
set_property PACKAGE_PIN P3 [get_ports {reg_value[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_value[12]}]
	
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
	
	
set_property PACKAGE_PIN U2 [get_ports {anode[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
	